apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rosen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rosenkrmnv/k3d.git
    targetRevision: HEAD
    path: Applications
  destination:
    server: https://kubernetes.default.svc
    namespace: applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
